export const Quotes = [
  "“Astrology reveals the will of the gods.”",
  "“Astrology is just a finger pointing at reality.”",
  "“The starry vault of heaven is in truth the open book of cosmic projection…”",
  "“Your path is illuminated by a road-map of stars. I am here to guide you!”",
  "“There is no better boat than a horoscope to help a man cross over the sea of life.”",
  "“I will look on the stars and look on thee, and read the page of thy destiny.”",
  "A person can achieve everything by being simple and humble. -Rig Veda",
  "“When there is harmony between the mind, heart, and resolution, then nothing is impossible. – Rig Veda”",
  "“Do not be led by others, awaken your own mind, amass your own experience, and decide for yourself your own path. – Atharva Veda”",
  "The person who is always involved in good deeds experiences incessant divine happiness. – Rig Veda",
  "Truth can not be suppressed and always is the ultimate victor. – Yajur Veda",
  "One should respect his motherland, his culture and his mother tongue because they are givers of happiness. – Rig Veda",
  "“Even God blesses only those who are contemplative, intelligent and the protectors of the weak. – Rig Veda”",
  "“Ego is the biggest enemy of humans. – Rig Veda”",
  "“Intelligence is the mightiest and nothing is beyond its reach. – Rig Veda”",
  "“Strive to move away from untruth towards truth. – Atharva Veda”",
  "“A man’s growth and progress will be hindered if he does not have a pure-mind and a clean body. – Sam Veda”",
  "“Good thought can be imbibed by reading and studying good books and by contemplating on them. – Yajur Veda”",
  "“There comes a time when a man has to stand and fight! That time is when his friends’ dreams are being laughed at! And I won’t let you laugh at that! – Usopp”",
  "“Man or Child, Strong or Weak, None of those matters once you are out at sea! – Usopp”",
  "“All for one, one for all! There are times when a man has no choice but to act! – Brook”",
  "“Stand up right away! And don’t act like you’re about to die! It’s not like you! – Usopp”",
  "“Fools who don’t respect the past are likely to repeat it. – Nico Robin”",
  "“No matter how deep the night, it always turns to day, eventually. – Brook”",
  "“Don’t start a fight if you can’t end it. – Sanji”",
  "“You sure can talk the talk, but you’re not quite ready to walk the walk. Time’s up, it’s my turn. – Roronoa Zoro”",
  "“Being strong isn’t just about having power or move, it about one’s spirit. – Roronoa Zoro”",
  "“When you decided to go to the sea, it was your own decision. Whatever happens to you on the sea, it depends on what you’ve done! Don’t blame others! – Roronoa Zoro”",
  "“I don’t care what the society says. I’ve never regretted doing anything. I will survive and do what I want to. – Roronoa Zoro”",
  "“Bring on the hardship. It’s preferred in a path of carnage. – Roronoa Zoro”",
  "“You need to accept the fact that you’re not the best and have all the will to strive to be better than anyone you face. – Roronoa Zoro”",
  "“When I decided to follow my dream I had already discarded my life. – Roronoa Zoro”",
  "“If you don’t take risks, you can’t create a future. – Monkey D. Luffy (One Piece)”",
  "“If I give up now, I’m going to regret it. – Monkey D. Luffy”",
  "“If I die fighting for it, that’s fine. I will fight… – Monkey D. Luffy”",
  "“I’ve set myself to become the King of Pirates… and if I die trying… then at least I tried. – Monkey D. Luffy”",
  "“I don’t want to conquer anything. I just think the guy with the most freedom in this whole ocean… is the Pirate King! – Monkey D. Luffy”",
  "“ower isn’t determined by your size, but the size of your heart and dreams. – Monkey D. Luffy”",
  "“No matter how hard or how impossible it is, never lose sight of your goal. – Monkey D. Luffy”",
  "“It’s not about whether it’s impossible or not, I’m doing it because I want to. – Monkey D. Luffy”",
];
